baseURL: "https://rwater.house" # url address of the website | required
languageCode: "en-us" # recommended | no default
title: "Russell Waterhouse" # title of the site; usually same as brand name | required
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

taxonomies:
  tag: "tags"

pagination:
  pagerSize: 3

# Allow HTML in markdown to be rendered, for social platform list in configuration options
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2

Menus:
  main:
    - identifier: posts
      name: Posts
      title: Blog posts
      url: /post
      weight: 1
    # - identifier: about
    #   name: About the Author
    #   title: About the Author
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Building Better Products
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Russell Waterhouse | Building Better Products" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Russell."
    subtitle: "I make great software."
    content: ""
    image: /images/pizzas.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    # button:
    #   enable: true
    #   name: "Resume"
    #   url: "#"
    #   download: true
    #   newPage: false
    # socialLinks:
    #   fontAwesomeIcons:
    #     - icon: fab fa-github
    #       url: https://example.com
    #     - icon: fab fa-x-twitter
    #       url: https://example.com
    #   customIcons:
    #     - icon: /fav.png
    #       url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/pizzas.png"
    content: |-
      I am a software developer specializing in developing high-reliability zero-defect software. I work in the medical device field, where we don't tolerate buggy, unreliable software.

      I bring this committment to excellence to everything that I do.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Docker"
        - "Kubernetes"
        - "Terraform"
        - "Azure"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  footer:
    recentPosts:
      path: "post"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #   instagram: https://instagram.com
    #   facebook: https://facebook.com

  # # List pages like blogs and posts
  # listPages:
  #   disableFeaturedImage: false

  # Single pages like blog and post
  # singlePages:
  #   socialShare: true
  #   readTime:
  #     enable: true
  #     content: "min read"
  #   scrollprogress:
  #     enable: true
  #   tags:
  #     openInNewTab: true

  # For translations
  # terms:
  #   read: "Read"
  #   toc: "Table Of Contents"
  #   copyright: "All rights reserved"
  #   pageNotFound: "Page not found"
  #   emailText: "Check out this site"

  # datesFormat:
  #   article: "Jan 2, 2006"
  #   articleList: "Jan 2, 2006"
  #   articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
